#!/bin/bash
# Post-install message with next steps

echo ""
echo "============================================"
echo "  cert-manager Operator Installed!"
echo "============================================"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Wait for operator to be ready:"
echo ""
echo "   kubectl wait --for=condition=available deployment/cert-manager-operator-controller-manager -n cert-manager-operator --timeout=120s"
echo ""
echo "2. The operator will automatically create a CertManager CR and deploy cert-manager components."
echo "   Check status:"
echo ""
echo "   kubectl get certmanager cluster -o yaml"
echo "   kubectl get pods -n cert-manager"
echo ""
echo "3. Create an Issuer or ClusterIssuer to start issuing certificates:"
echo ""
echo "   # Example self-signed ClusterIssuer:"
echo "   kubectl apply -f - <<EOF"
echo "   apiVersion: cert-manager.io/v1"
echo "   kind: ClusterIssuer"
echo "   metadata:"
echo "     name: selfsigned-issuer"
echo "   spec:"
echo "     selfSigned: {}"
echo "   EOF"
echo ""
echo "See README.md for full documentation."
echo "============================================"
echo ""
